language: node_js
node_js:
- '8'
install:
- npm install
branches:
  only:
  - master
deploy:
  provider: heroku
  app: cidc-line-bot
  api_key:
    secure: ijLV068SJr71eD+cINuZRTWl6Tae39UNUGNYm7QfNJ4jaOgqeyFlmjqbpYNaIAG1erc228TJm99QaXIik2m9tWAsmNwOhIcrB6DFdjaQB7p7ZQkJdtWl2m7V5rHnMYDKYBBgJz4Ni5ojJd4LQf4D+bDDv0UrhcBcUht2DMRXE+SgWo8WTXG1/nr03FD/CnUJopqYlEy9swFnC0EMW0gvfGJEWUUyfwb/lf36OTcqOSHNzopkV30Nj+Cf5O1+BTemD7gKG3q1zQXJPhdU52Y3RhqFL5VC7FON1gVibQRyLaLItfwrMZDOZy4lROEd8eM6D2Mimu5z51Yx3JrA0/eXEXbVN3evsnKXkJS8iB0R9y3JcRC473Pyh+5EPzKxkkVNfBCbLQwd7WORGBAlexdGBhf1EnkucXKAmb3IPucctGe5aWMF7MfT4OSYkU6Zix3gT25KcBb8UNQTCblSHJvR9h40vbEARt1aq9ZrGFqNQZ53ZhrXZYyBSWi2zcicOk6HFyKUSMcApfNxZiRhVy1R8gUPjksnD1S4PfzDM12gG6lbY5sUr5ja9R2VJ/fRbfmHjRI72Ky6Ic80Dq8qw7IC0fuNGCtniBMcfRlj+8E0ZM2OXYFdRuk2fD5uCiHKyoW5cCqY9z1A5v1zMEu4xg1rYirE1Xu6IPfNiN+UjsOz29s=
